import keyMirror from 'keymirror';

export default keyMirror({

  //Product related errors
  PRODUCTS_PRODUCT_ERROR: null,
  PRODUCTS_PRODUCT_INVALID: null,

  //Product view
  PRODUCTS_PRODUCT_LOAD_START:       null,
  PRODUCTS_PRODUCT_PLATFORMS_LOADED: null,
  PRODUCTS_PRODUCT_LOADED:           null,
  PRODUCTS_PRODUCT_LOAD_END:         null,

  //Product Sources
  PRODUCTS_PRODUCT_SOURCES_DOWNLOADED: null,

  //Product Delete
  PRODUCTS_PRODUCT_DELETED:   null,

  //Product form
  PRODUCTS_PRODUCT_FORM_CREATE:      null,
  PRODUCTS_PRODUCT_FORM_EDIT_START:  null,
  PRODUCTS_PRODUCT_FORM_CHANGED:     null,
  PRODUCTS_PRODUCT_FORM_SAVE_START:  null,
  PRODUCTS_PRODUCT_FORM_SAVE_END:    null,
  PRODUCTS_PRODUCT_FORM_SAVE_SUCCESS:null,
  PRODUCTS_PRODUCT_FORM_DISCARD:     null,
  PRODUCTS_PRODUCT_FORM_EDIT_END:    null,

  PRODUCTS_PRODUCT_FORM_CHILDREN_EDIT_DISCARD:                null,
  PRODUCTS_PRODUCT_FORM_CHILDREN_INTEGRATED_DISABLED_CHANGED: null,

  //Product form properties
  PRODUCTS_PRODUCT_FORM_PROPERTY_CREATE:     null,
  PRODUCTS_PRODUCT_FORM_PROPERTY_REMOVE:     null,
  PRODUCTS_PRODUCT_FORM_PROPERTY_EDIT_START: null,
  PRODUCTS_PRODUCT_FORM_PROPERTY_SAVE:       null

});
