import keyMirror from 'keymirror';

export default keyMirror({

  //Platform related errors
  PLATFORMS_PLATFORM_ERROR: null,

  //Platform view
  PLATFORMS_PLATFORM_LOAD_START:       null,
  PLATFORMS_PLATFORM_PLATFORMS_LOADED: null,
  PLATFORMS_PLATFORM_LOADED:           null,
  PLATFORMS_PLATFORM_LOAD_END:         null,

  PLATFORMS_PLATFORM_FORM_CHILDREN_EDIT_DISCARD: null,

  //Platform from sensors
  PLATFORMS_PLATFORM_FORM_PROPERTY_CREATE:     null,
  PLATFORMS_PLATFORM_FORM_PROPERTY_REMOVE:     null,
  PLATFORMS_PLATFORM_FORM_PROPERTY_EDIT_START: null,
  PLATFORMS_PLATFORM_FORM_PROPERTY_SAVE:       null,

});
